"""
Mock AI Provider – untuk pengembangan dan pengujian tanpa API eksternal.
"""

import logging
import json
from .base_client import BaseAIClient
from .models import AIRequest, AIResponse

logger = logging.getLogger(__name__)

MOCK_RESPONSE = {
    "questions": [
        {
            "question": "This is a mock question.",
            "choices": [
                "Option A",
                "Option B",
                "Option C",
                "Option D"
            ],
            "answer": "A",
            "explanation": "This answer is generated by Mock AI."
        }
    ]
}

class MockClient(BaseAIClient):
    """Provider tiruan yang mengembalikan respons tetap. Tidak memerlukan API key atau internet."""

    def __init__(self):
        self._initialized = False
        self._model_name = "mock-model"

    async def initialize(self) -> None:
        self._initialized = True
        logger.info("Mock provider initialized.")

    async def generate(self, request: AIRequest) -> AIResponse:
        logger.info("Mock request started.")
        # Abaikan prompt sepenuhnya, selalu kembalikan respons yang sama
        response_text = json.dumps(MOCK_RESPONSE, indent=2)
        logger.info("Mock response generated.")
        return AIResponse(
            response_text=response_text,
            provider="mock",
            metadata={
                "model": self._model_name,
                "finish_reason": "stop",
                "usage": {
                    "prompt_tokens": 0,
                    "completion_tokens": len(response_text.split()),
                    "total_tokens": len(response_text.split()),
                },
            },
        )

    async def health_check(self) -> bool:
        return self._initialized

    async def close(self) -> None:
        self._initialized = False
        logger.info("Mock provider closed.")