from typing import List, Dict, Any
from ..models import ExportDocument, ExportMetadata
from .base_formatter import BaseFormatter

class RichFormatter(BaseFormatter):
    """Formatter untuk dokumen kaya (dengan sections, cocok untuk PDF/DOCX)."""

    async def format(self, questions: List[Dict[str, Any]], metadata: ExportMetadata,
                     title: str = "Generated Questions") -> ExportDocument:
        sections = []
        # Section judul
        sections.append({
            "type": "heading",
            "level": 1,
            "content": title
        })
        # Metadata section
        meta_items = []
        if metadata.provider:
            meta_items.append(f"Provider: {metadata.provider}")
        if metadata.model:
            meta_items.append(f"Model: {metadata.model}")
        if metadata.generation_time:
            meta_items.append(f"Generation Time: {metadata.generation_time:.2f}s")
        if meta_items:
            sections.append({
                "type": "paragraph",
                "content": " | ".join(meta_items)
            })

        # Setiap pertanyaan sebagai section
        for idx, q in enumerate(questions, start=1):
            q_sections = []
            q_sections.append({
                "type": "heading",
                "level": 2,
                "content": f"Question {idx}"
            })
            q_sections.append({
                "type": "paragraph",
                "content": q.get("question", "")
            })
            choices = q.get("choices")
            if choices:
                items = []
                for choice in choices:
                    label = choice.get('label', '')
                    text = choice.get('text', '')
                    items.append(f"{label}. {text}")
                q_sections.append({
                    "type": "list",
                    "ordered": False,
                    "items": items
                })
            answer = q.get("answer")
            if answer:
                q_sections.append({
                    "type": "paragraph",
                    "content": f"**Answer:** {answer}"
                })
            explanation = q.get("explanation")
            if explanation:
                q_sections.append({
                    "type": "paragraph",
                    "content": f"**Explanation:** {explanation}"
                })
            sections.append({
                "type": "group",
                "sections": q_sections
            })

        metadata.formatter_name = "rich"
        metadata.formatter_version = "1.0"
        # Kita tetap isi content dengan representasi sederhana (bisa dikosongkan)
        content = title  # placeholder
        return ExportDocument(
            title=title,
            content=content,
            questions=questions,
            metadata=metadata,
            sections=sections,
            footer=f"Generated by OpenQuiz AI using {metadata.provider or 'unknown'} provider."
        )

    def supports(self, format_name: str) -> bool:
        return format_name == "rich"

    def description(self) -> str:
        return "Rich document formatter (sections-based)"