"""
PDF Exporter menggunakan ReportLab.
Mengonsumsi ExportDocument dan menghasilkan file PDF.
"""

import io
import logging
from typing import Optional
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    PageBreak, KeepTogether
)
from reportlab.lib import colors
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont

from ..base_exporter import BaseExporter
from ..models import ExportDocument, ExportResult, ExportStatus, ExportMetadata

from ..exceptions import ExportGenerationError

logger = logging.getLogger(__name__)

# Daftarkan font DejaVuSans untuk dukungan Unicode (Indonesia, aksen, dll.)
# Pastikan file font tersedia di sistem atau sertakan dalam proyek.
# Untuk kemudahan, kita gunakan font bawaan ReportLab yang terbatas.
# Jika perlu Unicode penuh, tambahkan file TTF dan ganti font di sini.
FONT_NAME = 'Helvetica'
FONT_BOLD = 'Helvetica-Bold'
FONT_SIZE_TITLE = 18
FONT_SIZE_HEADING = 14
FONT_SIZE_BODY = 11


class PDFExporter(BaseExporter):
    """Mengekspor ExportDocument ke PDF."""

    def __init__(self):
        self._initialized = False

    async def initialize(self) -> None:
        """Tidak ada resource khusus; langsung tandai siap."""
        self._initialized = True
        logger.info("PDFExporter initialized.")

    async def export(self, document: ExportDocument) -> ExportResult:
        """Hasilkan PDF dari ExportDocument."""
        if not self._initialized:
            raise ExportGenerationError("PDFExporter not initialized.")

        if not document.questions and not document.sections:
            raise ExportGenerationError("Document has no content to export.")

        buffer = io.BytesIO()
        try:
            doc = SimpleDocTemplate(
                buffer,
                pagesize=A4,
                topMargin=20 * mm,
                bottomMargin=20 * mm,
                leftMargin=15 * mm,
                rightMargin=15 * mm,
                title=document.title or "Generated Questions",
                author="OpenQuiz AI",
            )

            story = self._build_story(document)
            doc.build(story)
            pdf_content = buffer.getvalue()

            return ExportResult(
                status=ExportStatus.COMPLETED,
                format="pdf",
                content=pdf_content,
                content_type="application/pdf",
                filename=f"{document.title or 'questions'}.pdf",
            )
        except Exception as e:
            logger.error(f"PDF generation failed: {str(e)}")
            raise ExportGenerationError(f"Failed to generate PDF: {str(e)}") from e
        finally:
            buffer.close()

    def _build_story(self, document: ExportDocument) -> list:
        """Bangun daftar elemen platypus dari ExportDocument."""
        styles = getSampleStyleSheet()
        self._register_custom_styles(styles)

        story = []

        # Jika dokumen memiliki sections (dari RichFormatter), gunakan itu
        if document.sections:
            story.extend(self._render_sections(document.sections, styles))
        else:
            # Fallback ke konten teks + questions
            story.extend(self._render_from_content(document, styles))

        # Footer
        footer_text = document.footer or "Generated by OpenQuiz AI"
        story.append(Spacer(1, 10 * mm))
        story.append(Paragraph(footer_text, styles['Footer']))

        return story

    def _build_story(self, document: ExportDocument) -> list:
        styles = getSampleStyleSheet()
        self._register_custom_styles(styles)

        story = []
        # Metadata section (jika ada)
        story.extend(self._render_metadata(document.metadata, styles))

        if document.sections:
            story.extend(self._render_sections(document.sections, styles))
        else:
            story.extend(self._render_from_content(document, styles))

        footer_text = document.footer or "Generated by OpenQuiz AI"
        story.append(Spacer(1, 10 * mm))
        story.append(Paragraph(footer_text, styles['Footer']))

        return story

    def _render_metadata(self, metadata: ExportMetadata, styles: dict) -> list:
        """Render metadata sebagai paragraf di awal dokumen."""
        items = []
        if metadata.generated_at:
            items.append(f"Generated At: {metadata.generated_at}")
        if metadata.provider:
            items.append(f"Provider: {metadata.provider}")
        if metadata.model:
            items.append(f"Model: {metadata.model}")
        if metadata.generation_time is not None:
            items.append(f"Generation Time: {metadata.generation_time:.2f}s")
        if metadata.prompt_version:
            items.append(f"Prompt Version: {metadata.prompt_version}")
        if metadata.schema_version:
            items.append(f"Schema Version: {metadata.schema_version}")
        if metadata.question_count is not None:
            items.append(f"Question Count: {metadata.question_count}")
        if metadata.language:
            items.append(f"Language: {metadata.language}")
        if metadata.difficulty:
            items.append(f"Difficulty: {metadata.difficulty}")
        if metadata.session_id:
            items.append(f"Session ID: {metadata.session_id}")
        if metadata.request_id:
            items.append(f"Correlation ID: {metadata.request_id}")
        if metadata.formatter_name:
            items.append(f"Formatter: {metadata.formatter_name} v{metadata.formatter_version or '1.0'}")

        if not items:
            return []

        story = []
        story.append(Paragraph("Document Information", styles['Heading2']))
        for item in items:
            story.append(Paragraph(item, styles['BodyText']))
        story.append(Spacer(1, 5 * mm))
        return story

    def _render_from_content(self, document: ExportDocument, styles: dict) -> list:
        """Fallback: render dari content text dan questions."""
        story = []
        # Title
        if document.title:
            story.append(Paragraph(document.title, styles['Title']))
            story.append(Spacer(1, 5 * mm))

        # Metadata
        meta = document.metadata
        meta_lines = []
        if meta.provider:
            meta_lines.append(f"Provider: {meta.provider}")
        if meta.model:
            meta_lines.append(f"Model: {meta.model}")
        if meta.generation_time:
            meta_lines.append(f"Generation Time: {meta.generation_time:.2f}s")
        if meta.question_count is not None:
            meta_lines.append(f"Questions: {meta.question_count}")
        if meta_lines:
            for line in meta_lines:
                story.append(Paragraph(line, styles['BodyText']))
            story.append(Spacer(1, 5 * mm))

        # Questions
        for idx, q in enumerate(document.questions, start=1):
            story.append(Paragraph(f"Question {idx}", styles['Heading2']))
            story.append(Paragraph(q.get("question", ""), styles['BodyText']))
            choices = q.get("choices")
            if choices:
                for c in choices:
                    label = c.get("label", "")
                    text = c.get("text", "")
                    story.append(Paragraph(f"{label}. {text}", styles['BodyText']))
            answer = q.get("answer")
            if answer:
                story.append(Paragraph(f"<b>Answer:</b> {answer}", styles['BodyText']))
            explanation = q.get("explanation")
            if explanation:
                story.append(Paragraph(f"<b>Explanation:</b> {explanation}", styles['BodyText']))
            story.append(Spacer(1, 4 * mm))

        return story

    def _register_custom_styles(self, styles: dict):
        """Tambahkan style khusus jika belum ada."""
        if 'Footer' not in styles:
            styles.add(ParagraphStyle(
                name='Footer',
                parent=styles['Normal'],
                fontSize=8,
                alignment=TA_CENTER,
                textColor=colors.grey,
            ))

    def supports(self, format: str) -> bool:
        return format.lower() == "pdf"

    async def health_check(self) -> bool:
        return self._initialized

    async def close(self) -> None:
        self._initialized = False
        logger.info("PDFExporter closed.")