"""
PDF Exporter menggunakan ReportLab.
Mengonsumsi ExportDocument dan menghasilkan file PDF.
"""

import io
import logging
from typing import Optional
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    PageBreak, KeepTogether
)
from reportlab.lib import colors
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont

from ..base_exporter import BaseExporter
from ..models import ExportDocument, ExportResult, ExportStatus, ExportMetadata
from ..exceptions import ExportGenerationError

logger = logging.getLogger(__name__)

FONT_NAME = 'Helvetica'
FONT_BOLD = 'Helvetica-Bold'
FONT_SIZE_TITLE = 18
FONT_SIZE_HEADING = 14
FONT_SIZE_BODY = 11


class PDFExporter(BaseExporter):
    """Mengekspor ExportDocument ke PDF."""

    def __init__(self):
        self._initialized = False

    async def initialize(self) -> None:
        self._initialized = True
        logger.info("PDFExporter initialized.")

    async def export(self, document: ExportDocument) -> ExportResult:
        if not self._initialized:
            raise ExportGenerationError("PDFExporter not initialized.")

        if not document.questions and not document.sections:
            raise ExportGenerationError("Document has no content to export.")

        buffer = io.BytesIO()
        try:
            doc = SimpleDocTemplate(
                buffer,
                pagesize=A4,
                topMargin=20 * mm,
                bottomMargin=20 * mm,
                leftMargin=15 * mm,
                rightMargin=15 * mm,
                title=document.title or "Generated Questions",
                author="OpenQuiz AI",
            )

            story = self._build_story(document)
            doc.build(story)
            pdf_content = buffer.getvalue()

            return ExportResult(
                status=ExportStatus.COMPLETED,
                format="pdf",
                content=pdf_content,
                content_type="application/pdf",
                filename=f"{document.title or 'questions'}.pdf",
            )
        except Exception as e:
            logger.error(f"PDF generation failed: {str(e)}")
            raise ExportGenerationError(f"Failed to generate PDF: {str(e)}") from e
        finally:
            buffer.close()

    def _build_story(self, document: ExportDocument) -> list:
        styles = getSampleStyleSheet()
        self._register_custom_styles(styles)

        story = []

        # Metadata section
        story.extend(self._render_metadata(document.metadata, styles))

        if document.sections:
            story.extend(self._render_sections(document.sections, styles))
        else:
            story.extend(self._render_from_content(document, styles))

        # Footer
        footer_text = document.footer or "Generated by OpenQuiz AI"
        story.append(Spacer(1, 10 * mm))
        story.append(Paragraph(footer_text, styles['Footer']))

        return story

    def _render_metadata(self, metadata: ExportMetadata, styles: dict) -> list:
        """Render metadata sebagai paragraf di awal dokumen."""
        items = []
        if metadata.generated_at:
            items.append(f"Generated At: {metadata.generated_at}")
        if metadata.provider:
            items.append(f"Provider: {metadata.provider}")
        if metadata.model:
            items.append(f"Model: {metadata.model}")
        if metadata.generation_time is not None:
            items.append(f"Generation Time: {metadata.generation_time:.2f}s")
        if metadata.prompt_version:
            items.append(f"Prompt Version: {metadata.prompt_version}")
        if metadata.schema_version:
            items.append(f"Schema Version: {metadata.schema_version}")
        if metadata.question_count is not None:
            items.append(f"Question Count: {metadata.question_count}")
        if metadata.language:
            items.append(f"Language: {metadata.language}")
        if metadata.difficulty:
            items.append(f"Difficulty: {metadata.difficulty}")
        if metadata.session_id:
            items.append(f"Session ID: {metadata.session_id}")
        if metadata.request_id:
            items.append(f"Correlation ID: {metadata.request_id}")
        if metadata.formatter_name:
            items.append(f"Formatter: {metadata.formatter_name} v{metadata.formatter_version or '1.0'}")

        if not items:
            return []

        story = []
        story.append(Paragraph("Document Information", styles['Heading2']))
        for item in items:
            story.append(Paragraph(item, styles['BodyText']))
        story.append(Spacer(1, 5 * mm))
        return story

    def _render_sections(self, sections: list, styles: dict) -> list:
        """Render sections dari rich formatter."""
        story = []
        for section in sections:
            sec_type = section.get("type", "")
            if sec_type == "heading":
                level = section.get("level", 1)
                style_name = f'Heading{level}'
                story.append(Paragraph(section.get("content", ""), styles[style_name]))
                story.append(Spacer(1, 2 * mm))
            elif sec_type == "paragraph":
                story.append(Paragraph(section.get("content", ""), styles['BodyText']))
                story.append(Spacer(1, 1 * mm))
            elif sec_type == "list":
                items = section.get("items", [])
                ordered = section.get("ordered", False)
                for i, item in enumerate(items, 1):
                    prefix = f"{i}." if ordered else "•"
                    text = f"{prefix} {item}"
                    story.append(Paragraph(text, styles['BodyText']))
                story.append(Spacer(1, 2 * mm))
            elif sec_type == "group":
                story.extend(self._render_sections(section.get("sections", []), styles))
                story.append(Spacer(1, 4 * mm))
        return story

    def _render_from_content(self, document: ExportDocument, styles: dict) -> list:
        """Fallback: render dari content text dan questions."""
        story = []
        if document.title:
            story.append(Paragraph(document.title, styles['Title']))
            story.append(Spacer(1, 5 * mm))

        # Metadata already rendered above, so skip here.

        for idx, q in enumerate(document.questions, start=1):
            story.append(Paragraph(f"Question {idx}", styles['Heading2']))
            story.append(Paragraph(q.get("question", ""), styles['BodyText']))
            choices = q.get("choices")
            if choices:
                for c in choices:
                    label = c.get("label", "")
                    text = c.get("text", "")
                    story.append(Paragraph(f"{label}. {text}", styles['BodyText']))
            answer = q.get("answer")
            if answer:
                story.append(Paragraph(f"<b>Answer:</b> {answer}", styles['BodyText']))
            explanation = q.get("explanation")
            if explanation:
                story.append(Paragraph(f"<b>Explanation:</b> {explanation}", styles['BodyText']))
            story.append(Spacer(1, 4 * mm))

        return story

    def _register_custom_styles(self, styles: dict):
        if 'Footer' not in styles:
            styles.add(ParagraphStyle(
                name='Footer',
                parent=styles['Normal'],
                fontSize=8,
                alignment=TA_CENTER,
                textColor=colors.grey,
            ))

    def get_capabilities(self):
        from ..capabilities import ExportCapability
        return ExportCapability(
            exporter_name="PDFExporter",
            exporter_version="1.0.0",
            capability_version="1.0",
            supports_rich_text=True,
            supports_pagination=True,
            supports_headers=True,
            supports_footers=True,
            supports_page_numbers=True,
            supports_metadata=True,
            supports_unicode=True,
            supports_compression=True,
            supports_preview=True,
            supports_large_documents=True,
            supported_extensions=[".pdf"],
            preferred_file_extension=".pdf",
            max_recommended_questions=500,
            display_name="PDF Document",
            description="Portable Document Format untuk cetak dan distribusi."
        )

    def supports(self, format: str) -> bool:
        return format.lower() == "pdf"

    async def health_check(self) -> bool:
        return self._initialized

    async def close(self) -> None:
        self._initialized = False
        logger.info("PDFExporter closed.")